### ISSUE TITLE
Missed parts of documentation

### ISSUE THREAD

**Issue by ChameleonTartu** [bgusach/ryanscan#1]
I found the project and wanted to try it out to do searches for different subsets of data. 
- Could you possibly update documentation, so it would be clear what technical requirements are required?
- What version of Python to use and do I need virtualenv or anything else to run it?
- Could you specify what platforms it was written for and if project is supported or not?
- Do you need any contribution to it?

**Comment by bgusach** [comment]
Hi there,

I enhanced a little bit the README file. It should be good enough now. 

There are some TODOs at the end of the README, maybe you can take a look at them. Or feel free to improve things and make a pull request.

**Comment by ChameleonTartu** [comment]
@bgusach Thank you for the updated documentation. I need a bit more time to dive deeper into the code logic. I am planning to contribute to this project, since it is very interesting.

**Comment by bgusach** [comment]
Nice! If you have any question, don't hesitate to shoot. 

You can find my email in any commit. For now I'm going to close this issue.
